Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07683a44e80cd32c5
      InstanceType: t2.micro
      KeyName: cfn-workshop
      SecurityGroupIds: 
        - Fn::ImportValue: CFNWorkshop-BaselineSG
      SubnetId: 
        Fn::ImportValue: CFNWorkshop-PublicSubnet2